spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/eye-tracking}
    username: ${DATABASE_USERNAME:POSTGRES}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties:
        hibernate:
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
          temp:
            use_jdbc_metadata_defaults: false
      hibernate:
        ddl-auto: none
      show-sql: true
